### ISSUE TITLE
Gestión de foro

### ISSUE THREAD

**Issue by AlmuGSancha** [Missionpage/sw-practices#31]
- Vista foro
- Añadir entrada
- Responder entrada
- Eliminar entrada (usuario propietario y admin)
- Eliminar respuesta (usuario propietario y admin)

**Comment by Triciabars** [comment]
- [ ] Crear clase Mensajes con refactorización
- [ ] Crear toda la gestión del foro de 0
- [ ] ... que lo rellene quien le toque
